name: 'CI'

on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build ./build
      - run: cmake --build ./build --target test